modLoader="javafml"
loaderVersion="[30,)"
issueTrackerURL="https://github.com/CodenameRevy/MagicMirrors/issues"

[[mods]]
modId="magicmirror"
version="${file.jarVersion}"
displayName="Magic Mirrors"
displayURL="https://github.com/CodenameRevy/MagicMirrors"
logoFile="logo.png"
credits="MichaelLimaRodrigues"
authors="CodenameRevy"
description='''
Magic Mirror mod adds several new items that are used to teleport you to your bed location almost instantly!
'''

[[dependencies.magicmirror]]
    modId="forge"
    mandatory=true
    versionRange="[30,)"
    ordering="NONE"
    side="BOTH"

[[dependencies.magicmirror]]
    modId="minecraft"
    mandatory=true
    versionRange="[1.15.1]"
    ordering="NONE"
    side="BOTH"
